support for SIARDDK and cas dependencies update
keeps/dbptk-ui pull request #431
Opened 2024-11-25 13:27 UTC by AntonioG70

2024-11-29 16:37 UTC, 006627 requested changes

2024-11-29 16:37 UTC, 006627 commented on src/main/java/com/databasepreservation/common/server/controller/SIARDController.java
> +      if (siardVersion.equals(ViewerConstants.SIARD_DK)) {
In some parts of the code you are comparing with SIARD_DK, and in other parts with SIARD_DK_128 and SIARD_DK_1007, this is creating confusion for me to understand the flow of your code, this will make the maintenance of the code problematic, since whoever needs to call the methods that require the version will not know for sure if internally you are doing the verification for SIARD_DK_128 and SIARD_DK_1007 or only for SIARD_DK

2024-11-29 16:37 UTC, 006627 commented on src/main/java/com/databasepreservation/common/transformers/ToolkitStructure2ViewerStructure.java
> +          isSiardDK = true;
You just change the value of this variable here, which can create confusion for anyone reading the code above and may think that there is a possibility of it being a siardDK before reaching this part of the code.
If the changes to the behavior of the detectMimeType method are substantial because of whether it is siardDK or not, consider creating a new method instead of passing a boolean as a parameter.

2024-11-29 16:37 UTC, 006627 commented on src/main/java/com/databasepreservation/common/transformers/ToolkitStructure2ViewerStructure.java
> +    boolean blobIsInsideSiard, boolean isSiardDK) {
If the changes to the behavior of the detectMimeType method are substantial because of whether it is siardDK or not, consider creating a new method instead of passing a boolean as a parameter.

2024-11-29 16:37 UTC, 006627 commented on src/main/java/com/databasepreservation/common/utils/LobManagerUtils.java
> +          throw new RuntimeException(e);
Please avoid throwing a RuntimeException here. Runtime exceptions are typically reserved for unexpected scenarios or system-level issues that cannot be reasonably anticipated or handled.

2024-12-02 11:10 UTC, AntonioG70 commented on src/main/java/com/databasepreservation/common/api/v1/CollectionResource.java
>            return handleExternalLobDownload(configTable, row, columnIndex);
No, the lobs have to be inside the Documents folder on the main SIARD folder.

2024-12-02 11:10 UTC, AntonioG70 commented on src/main/java/com/databasepreservation/common/api/v1/FileResource.java
> +    } catch (IOException e) {
Done.

2024-12-02 11:11 UTC, AntonioG70 commented on src/main/java/com/databasepreservation/common/client/services/CollectionService.java
> +  StringResponse createCollection(@PathVariable(name = "databaseUUID") String databaseUUID,
Done.

2024-12-02 11:11 UTC, AntonioG70 commented on src/main/java/com/databasepreservation/common/transformers/ToolkitStructure2ViewerStructure.java
> +          isSiardDK = true;
Done.

2024-12-02 11:11 UTC, AntonioG70 commented on src/main/java/com/databasepreservation/common/transformers/ToolkitStructure2ViewerStructure.java
> +    boolean blobIsInsideSiard, boolean isSiardDK) {
Done.

2024-12-02 11:11 UTC, AntonioG70 commented on src/main/java/com/databasepreservation/common/utils/LobManagerUtils.java
> +          throw new RuntimeException(e);
Done.

2024-12-02 13:09 UTC, AntonioG70 commented on src/main/java/com/databasepreservation/common/transformers/ToolkitStructure2ViewerStructure.java
> +        }
Done.

2024-12-02 13:10 UTC, AntonioG70 commented on src/main/java/com/databasepreservation/common/client/services/DatabaseService.java
> +  StringResponse create(@Parameter(name = "path") @RequestParam(name = "path") String path,
Done.

2024-12-02 13:10 UTC, AntonioG70 commented on src/main/java/com/databasepreservation/common/server/controller/SIARDController.java
> +      if (siardVersion.equals(ViewerConstants.SIARD_DK)) {
Done.

2024-12-02 13:22 UTC, AntonioG70 commented on src/main/java/com/databasepreservation/common/transformers/ToolkitStructure2ViewerStructure.java
> +      }
Done.

2024-12-02 15:29 UTC, 006627 approved these changes

2024-12-02 15:29 UTC, merged