Search all frontend implementation
keeps/dbptk-ui pull request #440
Opened 2024-12-04 10:13 UTC by SugaryLump

- Adds a panel for database selection in cross search
    - `SearchPanel` has been changed to be an implementation of new abstract class `SearchPanelAbstract`
    - A new implementation of `SearchPanel` was made for cross search purposes, that has the database selection button
    - `UserDatabaseListPanel` and `DatabaseManage` have been modified according to the UI changes
    - Adds an optional item selection mode to `AsyncTableCell` that persists selections by keeping a set of selected object UUIDs (**previous functionality should remain unchanged, as long as this mode isn't toggled by setting the relevant flag**)
- Fixes a bug with `OneOfMany` filter parameters

2024-12-04 16:57 UTC, 006627 requested changes

2024-12-04 16:57 UTC, 006627 commented on src/main/java/com/databasepreservation/common/client/ViewerConstants.java
> +  public static final String PROPERTY_SEARCHALL_DEFAULTSELECTION = "ui.searchAll.defaultSelection";
Please separate words with underscore

2024-12-04 16:57 UTC, 006627 commented on src/main/java/com/databasepreservation/common/api/v1/DatabaseResource.java
> +      simpleFacetParameter.setOffset(findRequest.sublist.getFirstElementIndex());
Why is this line duplicated?

2024-12-04 16:57 UTC, 006627 commented on src/main/java/com/databasepreservation/common/client/common/dialogs/DatabaseSelectDialog.java
> +    setText("Select databases to search");
I believe this should come from the messages too, so you can use the translations.

2024-12-04 16:57 UTC, 006627 commented on src/main/java/com/databasepreservation/common/client/common/lists/DatabaseSelectList.java
> + * @author Bruno Ferreira <bferreira@keep.pt>
You should be the author of this class. This class and DatabaseList are very similar, if you have time, please refactor these classes to avoid duplicate code.

2024-12-04 16:57 UTC, 006627 commented on src/main/java/com/databasepreservation/common/client/common/search/SearchPanelWithSearchAll.java
> +import com.google.gwt.user.client.ui.Widget;
Some imports seem to be unused, please autoformat your code

2024-12-04 16:57 UTC, 006627 commented on src/main/java/com/databasepreservation/common/client/common/visualization/manager/databasePanel/user/UserDatabaseListPanel.java
> +import org.roda.core.data.v2.index.sublist.Sublist;
Some imports seem to be unused, please autoformat your code

2024-12-04 16:57 UTC, 006627 commented on src/main/resources/config/dbvtk-viewer.properties
> +# Search All settings
Add the allowed options here in this header and explain the behavior for each option

2024-12-04 16:57 UTC, 006627 commented on src/main/resources/config/dbvtk-viewer.properties
> +#ui.searchAll.defaultSelection=none
remove this line

2024-12-04 16:57 UTC, 006627 commented on src/main/resources/config/i18n/client/ClientMessages.properties
> +manageDatabaseSearchAllContactInfo=Contact your administrator to load databases or to request changes.
Please add messages in Portuguese for these new entries.

2024-12-05 09:25 UTC, SugaryLump commented on src/main/java/com/databasepreservation/common/client/common/dialogs/DatabaseSelectDialog.java
> +    this.hide();
Change behavior to conform with client's requested changes

2024-12-09 11:21 UTC, 006627 requested changes

2024-12-09 11:21 UTC, 006627 commented on src/main/java/com/databasepreservation/common/api/v1/DatabaseResource.java
> +import com.databasepreservation.common.api.exceptions.RESTException;
Please remove imports that are not being used

2024-12-09 11:25 UTC, 006627 approved these changes

2024-12-09 11:27 UTC, merged